### ISSUE TITLE
Not restoring playing after notification

### ISSUE THREAD

**Issue by jsponz** [svrooij/sonos2mqtt#22]
I am listening to the music. 

I play the notification using the given example, but after playing the notification, the music is not restore and I get this error message. 

1|bridge  | { Error: Request failed with status code 500
1|bridge  |     at createError (/home/pi/.nvm/versions/node/v10.16.1/lib/node_modules/sonos2mqtt/node_modules/axios/lib/core/createError.js:16:15)
1|bridge  |     at settle (/home/pi/.nvm/versions/node/v10.16.1/lib/node_modules/sonos2mqtt/node_modules/axios/lib/core/settle.js:18:12)
1|bridge  |     at IncomingMessage.handleStreamEnd (/home/pi/.nvm/versions/node/v10.16.1/lib/node_modules/sonos2mqtt/node_modules/axios/lib/adapters/http.js:202:11)
1|bridge  |     at IncomingMessage.emit (events.js:203:15)
1|bridge  |     at endReadableNT (_stream_readable.js:1145:12)
1|bridge  |     at process._tickCallback (internal/process/next_tick.js:63:19)
1|bridge  |   config:
1|bridge  |    { adapter: [Function: httpAdapter],
1|bridge  |      transformRequest: { '0': [Function: transformRequest] },
1|bridge  |      transformResponse: { '0': [Function: transformResponse] },
1|bridge  |      timeout: 0,
1|bridge  |      xsrfCookieName: 'XSRF-TOKEN',
1|bridge  |      xsrfHeaderName: 'X-XSRF-TOKEN',
1|bridge  |      maxContentLength: -1,
1|bridge  |      validateStatus: [Function: validateStatus],
1|bridge  |      headers:
1|bridge  |       { Accept: 'application/json, text/plain, */*',
1|bridge  |         'Content-Type': 'text/xml; charset=utf8',
1|bridge  |         SOAPAction: '"urn:schemas-upnp-org:service:AVTransport:1#Seek"',
1|bridge  |         'User-Agent': 'axios/0.18.1',
1|bridge  |         'Content-Length': 289 },
1|bridge  |      method: 'post',
1|bridge  |      url:
1|bridge  |       'http://192.168.2.181:1400/MediaRenderer/AVTransport/Control',
1|bridge  |      data:
1|bridge  |       '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:Seek xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID><Unit>TRACK_NR</Unit><Target>2</Target></u:Seek></s:Body></s:Envelope>' },
1|bridge  |   request:
1|bridge  |    ClientRequest {
1|bridge  |      _events:
1|bridge  |       [Object: null prototype] {
1|bridge  |         socket: [Function],
1|bridge  |         abort: [Function],
1|bridge  |         aborted: [Function],
1|bridge  |         error: [Function],
1|bridge  |         timeout: [Function],
1|bridge  |         prefinish: [Function: requestOnPrefinish] },
1|bridge  |      _eventsCount: 6,
1|bridge  |      _maxListeners: undefined,
1|bridge  |      output: [],
1|bridge  |      outputEncodings: [],
1|bridge  |      outputCallbacks: [],
1|bridge  |      outputSize: 0,
1|bridge  |      writable: true,
1|bridge  |      _last: true,
1|bridge  |      chunkedEncoding: false,
1|bridge  |      shouldKeepAlive: false,
1|bridge  |      useChunkedEncodingByDefault: true,
1|bridge  |      sendDate: false,
1|bridge  |      _removedConnection: false,
1|bridge  |      _removedContLen: false,
1|bridge  |      _removedTE: false,
1|bridge  |      _contentLength: null,
1|bridge  |      _hasBody: true,
1|bridge  |      _trailer: '',
1|bridge  |      finished: true,
1|bridge  |      _headerSent: true,
1|bridge  |      socket:
1|bridge  |       Socket {
1|bridge  |         connecting: false,
1|bridge  |         _hadError: false,
1|bridge  |         _handle: [TCP],
1|bridge  |         _parent: null,
1|bridge  |         _host: null,
1|bridge  |         _readableState: [ReadableState],
1|bridge  |         readable: true,
1|bridge  |         _events: [Object],
1|bridge  |         _eventsCount: 7,
1|bridge  |         _maxListeners: undefined,
1|bridge  |         _writableState: [WritableState],
1|bridge  |         writable: false,
1|bridge  |         allowHalfOpen: false,
1|bridge  |         _sockname: null,
1|bridge  |         _pendingData: null,
1|bridge  |         _pendingEncoding: '',
1|bridge  |         server: null,
1|bridge  |         _server: null,
1|bridge  |         parser: null,
1|bridge  |         _httpMessage: [Circular],
1|bridge  |         [Symbol(asyncId)]: 845,
1|bridge  |         [Symbol(lastWriteQueueSize)]: 0,
1|bridge  |         [Symbol(timeout)]: null,
1|bridge  |         [Symbol(kBytesRead)]: 0,
1|bridge  |         [Symbol(kBytesWritten)]: 0 },
1|bridge  |      connection:
1|bridge  |       Socket {
1|bridge  |         connecting: false,
1|bridge  |         _hadError: false,
1|bridge  |         _handle: [TCP],
1|bridge  |         _parent: null,
1|bridge  |         _host: null,
1|bridge  |         _readableState: [ReadableState],
1|bridge  |         readable: true,
1|bridge  |         _events: [Object],
1|bridge  |         _eventsCount: 7,
1|bridge  |         _maxListeners: undefined,
1|bridge  |         _writableState: [WritableState],
1|bridge  |         writable: false,
1|bridge  |         allowHalfOpen: false,
1|bridge  |         _sockname: null,
1|bridge  |         _pendingData: null,
1|bridge  |         _pendingEncoding: '',
1|bridge  |         server: null,
1|bridge  |         _server: null,
1|bridge  |         parser: null,
1|bridge  |         _httpMessage: [Circular],
1|bridge  |         [Symbol(asyncId)]: 845,
1|bridge  |         [Symbol(lastWriteQueueSize)]: 0,
1|bridge  |         [Symbol(timeout)]: null,
1|bridge  |         [Symbol(kBytesRead)]: 0,
1|bridge  |         [Symbol(kBytesWritten)]: 0 },
1|bridge  |      _header:
1|bridge  |       'POST /MediaRenderer/AVTransport/Control HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: text/xml; charset=utf8\r\nSOAPAction: "urn:schemas-upnp-org:service:AVTransport:1#Seek"\r\nUser-Agent: axios/0.18.1\r\nContent-Length: 289\r\nHost: 192.168.2.181:1400\r\nConnection: close\r\n\r\n',
1|bridge  |      _onPendingData: [Function: noopPendingOutput],
1|bridge  |      agent:
1|bridge  |       Agent {
1|bridge  |         _events: [Object],
1|bridge  |         _eventsCount: 1,
1|bridge  |         _maxListeners: undefined,
1|bridge  |         defaultPort: 80,
1|bridge  |         protocol: 'http:',
1|bridge  |         options: [Object],
1|bridge  |         requests: {},
1|bridge  |         sockets: [Object],
1|bridge  |         freeSockets: {},
1|bridge  |         keepAliveMsecs: 1000,
1|bridge  |         keepAlive: false,
1|bridge  |         maxSockets: Infinity,
1|bridge  |         maxFreeSockets: 256 },
1|bridge  |      socketPath: undefined,
1|bridge  |      timeout: undefined,
1|bridge  |      method: 'POST',
1|bridge  |      path: '/MediaRenderer/AVTransport/Control',
1|bridge  |      _ended: true,
1|bridge  |      res:
1|bridge  |       IncomingMessage {
1|bridge  |         _readableState: [ReadableState],
1|bridge  |         readable: false,
1|bridge  |         _events: [Object],
1|bridge  |         _eventsCount: 3,
1|bridge  |         _maxListeners: undefined,
1|bridge  |         socket: [Socket],
1|bridge  |         connection: [Socket],
1|bridge  |         httpVersionMajor: 1,
1|bridge  |         httpVersionMinor: 1,
1|bridge  |         httpVersion: '1.1',
1|bridge  |         complete: true,
1|bridge  |         headers: [Object],
1|bridge  |         rawHeaders: [Array],
1|bridge  |         trailers: {},
1|bridge  |         rawTrailers: [],
1|bridge  |         aborted: false,
1|bridge  |         upgrade: false,
1|bridge  |         url: '',
1|bridge  |         method: null,
1|bridge  |         statusCode: 500,
1|bridge  |         statusMessage: 'Internal Server Error',
1|bridge  |         client: [Socket],
1|bridge  |         _consuming: false,
1|bridge  |         _dumped: false,
1|bridge  |         req: [Circular],
1|bridge  |         responseUrl:
1|bridge  |          'http://192.168.2.181:1400/MediaRenderer/AVTransport/Control',
1|bridge  |         redirects: [] },
1|bridge  |      aborted: undefined,
1|bridge  |      timeoutCb: null,
1|bridge  |      upgradeOrConnect: false,
1|bridge  |      parser: null,
1|bridge  |      maxHeadersCount: null,
1|bridge  |      _redirectable:
1|bridge  |       Writable {
1|bridge  |         _writableState: [WritableState],
1|bridge  |         writable: true,
1|bridge  |         _events: [Object],
1|bridge  |         _eventsCount: 2,
1|bridge  |         _maxListeners: undefined,
1|bridge  |         _options: [Object],
1|bridge  |         _redirectCount: 0,
1|bridge  |         _redirects: [],
1|bridge  |         _requestBodyLength: 289,
1|bridge  |         _requestBodyBuffers: [],
1|bridge  |         _onNativeResponse: [Function],
1|bridge  |         _currentRequest: [Circular],
1|bridge  |         _currentUrl:
1|bridge  |          'http://192.168.2.181:1400/MediaRenderer/AVTransport/Control' },
1|bridge  |      [Symbol(isCorked)]: false,
1|bridge  |      [Symbol(outHeadersKey)]:
1|bridge  |       [Object: null prototype] {
1|bridge  |         accept: [Array],
1|bridge  |         'content-type': [Array],
1|bridge  |         soapaction: [Array],
1|bridge  |         'user-agent': [Array],
1|bridge  |         'content-length': [Array],
1|bridge  |         host: [Array] } },
1|bridge  |   response:
1|bridge  |    { status: 500,
1|bridge  |      statusText: 'Internal Server Error',
1|bridge  |      headers:
1|bridge  |       { 'content-length': '347',
1|bridge  |         'content-type': 'text/xml; charset="utf-8"',
1|bridge  |         ext: '',
1|bridge  |         server: 'Linux UPnP/1.0 Sonos/51.1-66240 (ZPS18)',
1|bridge  |         connection: 'close' },
1|bridge  |      config:
1|bridge  |       { adapter: [Function: httpAdapter],
1|bridge  |         transformRequest: [Object],
1|bridge  |         transformResponse: [Object],
1|bridge  |         timeout: 0,
1|bridge  |         xsrfCookieName: 'XSRF-TOKEN',
1|bridge  |         xsrfHeaderName: 'X-XSRF-TOKEN',
1|bridge  |         maxContentLength: -1,
1|bridge  |         validateStatus: [Function: validateStatus],
1|bridge  |         headers: [Object],
1|bridge  |         method: 'post',
1|bridge  |         url:
1|bridge  |          'http://192.168.2.181:1400/MediaRenderer/AVTransport/Control',
1|bridge  |         data:
1|bridge  |          '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:Seek xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID><Unit>TRACK_NR</Unit><Target>2</Target></u:Seek></s:Body></s:Envelope>' },
1|bridge  |      request:
1|bridge  |       ClientRequest {
1|bridge  |         _events: [Object],
1|bridge  |         _eventsCount: 6,
1|bridge  |         _maxListeners: undefined,
1|bridge  |         output: [],
1|bridge  |         outputEncodings: [],
1|bridge  |         outputCallbacks: [],
1|bridge  |         outputSize: 0,
1|bridge  |         writable: true,
1|bridge  |         _last: true,
1|bridge  |         chunkedEncoding: false,
1|bridge  |         shouldKeepAlive: false,
1|bridge  |         useChunkedEncodingByDefault: true,
1|bridge  |         sendDate: false,
1|bridge  |         _removedConnection: false,
1|bridge  |         _removedContLen: false,
1|bridge  |         _removedTE: false,
1|bridge  |         _contentLength: null,
1|bridge  |         _hasBody: true,
1|bridge  |         _trailer: '',
1|bridge  |         finished: true,
1|bridge  |         _headerSent: true,
1|bridge  |         socket: [Socket],
1|bridge  |         connection: [Socket],
1|bridge  |         _header:
1|bridge  |          'POST /MediaRenderer/AVTransport/Control HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: text/xml; charset=utf8\r\nSOAPAction: "urn:schemas-upnp-org:service:AVTransport:1#Seek"\r\nUser-Agent: axios/0.18.1\r\nContent-Length: 289\r\nHost: 192.168.2.181:1400\r\nConnection: close\r\n\r\n',
1|bridge  |         _onPendingData: [Function: noopPendingOutput],
1|bridge  |         agent: [Agent],
1|bridge  |         socketPath: undefined,
1|bridge  |         timeout: undefined,
1|bridge  |         method: 'POST',
1|bridge  |         path: '/MediaRenderer/AVTransport/Control',
1|bridge  |         _ended: true,
1|bridge  |         res: [IncomingMessage],
1|bridge  |         aborted: undefined,
1|bridge  |         timeoutCb: null,
1|bridge  |         upgradeOrConnect: false,
1|bridge  |         parser: null,
1|bridge  |         maxHeadersCount: null,
1|bridge  |         _redirectable: [Writable],
1|bridge  |         [Symbol(isCorked)]: false,
1|bridge  |         [Symbol(outHeadersKey)]: [Object] },
1|bridge  |      data:
1|bridge  |       '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>701</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>' } }

**Comment by svrooij** [comment]
This is probably related to https://github.com/bencevans/node-sonos/pull/430 will check it out next week. But this is in the sonos interface library and not in this library.

Could you provide extra information about the kind of music it want to revert back to?
There is a problem with radio streams because they don’t have an time or a number in the queue

**Comment by jsponz** [comment]
Thanks for your reply. 

I am listening to Amazon Music...

**Comment by svrooij** [comment]
As a stream or as single songs in a sonos playlists?

**Comment by jsponz** [comment]
stream... no radio or playlist...

**Comment by jsponz** [comment]
Any update on this?

**Comment by svrooij** [comment]
Since it's a stream this still applies:
> There is a problem with (radio) streams because they don’t have an time or a number in the queue.

Anyway this is an open-source project so you're free to submit a PR. There is also a [Paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=T9XFJYUSPE4SG) link on the readme if you want to convince me that I should spend some time fixing this issue now.

**Comment by svrooij** [comment]
This will be fixed when [this PR](https://github.com/bencevans/node-sonos/pull/440) has been accepted and released.

Then I'll only need to update the node-sonos version in this library.

**Comment by svrooij** [comment]
If you do an npm install sonos in the correct folder it should install sonos:1.12.3 and that should solve the issue.
Thanks for your support

**Comment by svrooij** [comment]
Commit 67d2d00

**Comment by jsponz** [comment]
I have updated both codes and I still have the same problem. Stream does not recover after playing notification.
