### ISSUE TITLE
response for mute and cmd switchtotv not working

### ISSUE THREAD

**Issue by heinz-otto** [svrooij/sonos2mqtt#97]
Hi Stephan,
Thanks for your sonos module.
I am evaluate the sonos2mqtt in connection with fhem.
There is unfortunately no response if I send mute to any speaker. All items "mute_" will be every time in state false. I have no idea why.

I have two players who switchtotv should working: beam and playbase
I will get every time the response not implemented (see error message)
I found two Items who may be a bug?
1. sonos-command-mapping.ts line 98 should there SwitchToTV instead of  SwitchToQueue?
2. https://github.com/svrooij/node-sonos-ts/blob/master/src/sonos-device.ts
Line 448 should there spdif instead of spdiff ?
Kindly regards 
Otto

Errormessage:
`[Warning] Error executing switchtotv for Wohnzimmer (RINCON_B8E93743FCBE01400)
 Error: Command 'switchtotv' not implemented
    at Function.ExecuteCommand (/home/pi/node_modules/sonos2mqtt/lib/sonos-command-mapping.js:99:23)
    at Function.ExecuteControl (/home/pi/node_modules/sonos2mqtt/lib/sonos-command-mapping.js:7:46)
    at EventEmitter.mqtt.Events.on (/home/pi/node_modules/sonos2mqtt/lib/sonos-to-mqtt.js:81:67)
    at EventEmitter.emit (events.js:198:13)
    at SmarthomeMqtt.handleIncomingMessage (/home/pi/node_modules/sonos2mqtt/lib/smarthome-mqtt.js:102:29)
    at MqttClient.mqttClient.on (/home/pi/node_modules/sonos2mqtt/lib/smarthome-mqtt.js:37:74)
    at MqttClient.emit (events.js:198:13)
    at MqttClient._handlePublish (/home/pi/node_modules/mqtt/lib/client.js:1162:12)
    at MqttClient._handlePacket (/home/pi/node_modules/mqtt/lib/client.js:351:12)
    at work (/home/pi/node_modules/mqtt/lib/client.js:283:12)`

**Comment by svrooij** [comment]
- Mute will be fixed soon (see https://github.com/svrooij/node-sonos-ts/issues/59)
- SwitchToTv was a bug in the sonos-command-mapping, good spot!

**Comment by svrooij** [comment]
@heinz-otto can you confirm your issues are fixed with this latest release? Then I will release a new latest version tomorrow.

**Comment by heinz-otto** [comment]
@Stephan The mute issue seems to be fixed. I have got a response :)
Unfortunately the switchtotv is still not working, there is another Error message, may be the same error, I think, if I tried to switch to the spdif line on behalf of  this command:
`{  "command": "adv-command", "input": { "cmd": "AVTransportService.SetAVTransportURI", "val": { "InstanceID": 0,"CurrentURI": `x-sonos-htastream:RINCON_347E5C82560801400:spdif`,CurrentURIMetaData: ''}}}
`

`0|sonos2mq | 2020-06-04T20:26:56.031Z [Warning] Error executing switchtotv for Arbeitszimmer (RINCON_347E5C82560801400)
0|sonos2mq |  { SonosError: Sonos error on SetAVTransportURI UPnPError 714
0|sonos2mq |     at AVTransportService.handleErrorResponse (/usr/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/services/base-service.js:209:23)
0|sonos2mq |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|sonos2mq |   Action: 'SetAVTransportURI',
0|sonos2mq |   FaultCode: 's:Client',
0|sonos2mq |   Fault: 'UPnPError',
0|sonos2mq |   UpnpErrorCode: 714,
0|sonos2mq |   name: 'SonosError' }`

**Comment by heinz-otto** [comment]
May be the x-sonos-htastream: is'nt correctly implemented? x-sonosapi-stream:, x-file-cifs:, and http: is working.

**Comment by svrooij** [comment]
There where 2 errors, fixed here https://github.com/svrooij/node-sonos-ts/commit/3478411e2a587366817f0f2629654923cc1baa9f

Will release a new beta later today.

**Comment by heinz-otto** [comment]
Greate Job! It works! Thanks a lot and have a nice day
